### ISSUE TITLE
Error: ELOCKED: File is locked

### ISSUE THREAD

**Issue by 4c656554** [holepunchto/pear#102]
Following the tutorial:

https://docs.pears.com/guides/starting-a-pear-desktop-project

On running:

`$ pear init --yes`

```
Installing Pear Runtime (Please stand by, this might take a bit...)
/usr/local/lib/node_modules/pear/node_modules/random-access-file/index.js:249
  const err = new Error('ELOCKED: File is locked')
              ^

Error: ELOCKED: File is locked
    at createLockError (/usr/local/lib/node_modules/pear/node_modules/random-access-file/index.js:249:15)
    at onopen (/usr/local/lib/node_modules/pear/node_modules/random-access-file/index.js:105:19)
    at FSReqCallback.oncomplete (node:fs:191:23) {
  code: 'ELOCKED',
  path: '/home/mydir/.config/pear/corestores/platform/primary-key'
}
```

Ubuntu 22.04.4 LTS 
amd64

I was also running keet the first time I tried this. The error persists when I close keet.

Is it a good idea to delete the lockfile?

What is the recommended course of action?

Thank you

**Comment by mafintosh** [comment]
close keet first, then wait 5 min and then run it for the first time.

**Comment by 4c656554** [comment]
Thanks, ended up rebooting - successfully installed Pear Runtime now :-)
