### ISSUE TITLE
GPU error

### ISSUE THREAD

**Issue by AMS777** [holepunchto/pear#227]
Hi guys,

I'm creating a basic demo, and I get following error:

```bash
[5135:0722/122801.206683:ERROR:command_buffer_proxy_impl.cc(128)] 
ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
```

![image](https://github.com/user-attachments/assets/b46cd85d-c572-4570-9e1a-df038468dfdc)

It usually only happens after the first run. So, the first run goes okay, second and following have the error.

The application launches though. But without devtools.

The machine is:
Ubuntu 24.04
VirtualBox 7.0.6

**Comment by papadakis-k** [comment]
Not accustomed with this project (I was just browsing the sources) but this issue might be related to hardware acceleration and issue #37 
Like the 1st comment suggests there, I would try to add the line
`electron.disableHardwareAcceleration();` 
Right after the require('electron') in electron-main.js and check if that fixes the problem.

Another idea is be to try Google Chrome inside the same VM and see if you can get hardware acceleration to work on it.

**Comment by davidmarkclements** [comment]
v0.4444.pqbzjhqyonxprx8hghxexnmctw75mr91ewqw5dxe1zmntfyaddqy release contains upgrade to electron 31, should solve the issue on linux (please reopen if not)
