### ISSUE TITLE
Devtools not showing

### ISSUE THREAD

**Issue by AMS777** [holepunchto/pear#228]
Hi guys,

I'm creating a basic demo. The application launches but the devtools don't show.

They should show by default, right?

Also, the flag `--no-devtools` doesn't seem to work:

![image](https://github.com/user-attachments/assets/7448e591-1035-40fa-8a68-4bf6ca81ae4a)

I was trying it, as the description says `Open devtools with application`, but I guess it's the other way around, it's to NOT open devtools?

The machine is:
Ubuntu 24.04
VirtualBox 7.0.6

**Comment by AMS777** [comment]
I saw that the devtools appear using the `--devtools` flag:

```
pear dev --devtools
```

But that flag is not listed as an option:

![image](https://github.com/user-attachments/assets/82771bd0-2a1c-4486-95dd-e81cf044559c)

Feel free to close this issue if there is nothing else to check.

**Comment by d61b292b-2859-4ed6-8c7c-b7397ad8e351** [comment]
`pear dev` does not open devtools.

`pear run --dev .` does open them. 

For people that are not aware, it's always possible to open devtools with ctrl+shift+i

**Comment by davidmarkclements** [comment]
release after next `pear dev` will be hard deprecated (will say to run pear run instead)
