### ISSUE TITLE
Feature request: Allow passing named arguments to pear run

### ISSUE THREAD

**Issue by d61b292b-2859-4ed6-8c7c-b7397ad8e351** [holepunchto/pear#256]
This would make it simpler to access passed arguments

https://docs.pears.com/pear-runtime/api#pear.config.args-less-than-array-greater-than

Probably a good idea to make it similar to `npm run`:

https://docs.npmjs.com/cli/v10/commands/npm-run-script

**Comment by davidmarkclements** [comment]
that's the job of a higher level library, such as https://github.com/holepunchto/paparam : `cmd.parse(Pear.config.args)`
