### ISSUE TITLE
Whitelist all http links for p2p app

### ISSUE THREAD

**Issue by kr-sandipprajapati** [holepunchto/pear#277]
In the current [peer. links](https://docs.pears.com/pear-runtime/configuration#pearlinks-objectarray) configuration, we are limited to adding some links to the whitelist. However, we need to whitelist all links. Please provide options or methods to achieve this.
we also add like this: "http://*" , "https://*"  to white list only HTTP or HTTPS link.

**Comment by annadevile** [comment]
hi! thanks, added to the roadmap :)
