### ISSUE TITLE
Some issues with Desktop Project

### ISSUE THREAD

**Issue by mattdesl** [holepunchto/pear#30]
Just starting with this guide:
https://docs.pears.com/guides/starting-a-pear-desktop-project

Noticed a couple issues on my machine when following:

1. Using `pear dev`, when I modify `index.html` and save the file, it does not trigger a live-reload in the open window. If I click the window and hit Cmd + R, it will reload and show the new markup.
2. Changing the `pear.gui.backgroundColor` has no effect; the background color is dark even when closing and re-running `pear dev`.
3. There doesn't appear to be a title like in the demo (the "DEV" button is not visible). See below.

<img width="768" alt="Screenshot 2024-02-16 at 15 23 01" src="https://github.com/holepunchto/pear/assets/1383811/73ec962c-6e19-4a7d-8f65-594a7bc2eebe">

specs:
macOS 13.0, node 21.6.2, npm 10.2.4

pear: 0.2494.pqbzjhqyonxprx8hghxexnmctw75mr91ewqw5dxe1zmntfyaddqy
bare: 1.0.0
uv: 1.48.0
v8: 11.8.172.16

**Comment by mafintosh** [comment]
Ya we are re-enabling live reload soon, we had a bug before launch so we had to disable tmp

**Comment by mafintosh** [comment]
For the title, we changed it, there is a controls element now for full control. Will let @davidmarkclements add more context

**Comment by davidmarkclements** [comment]
there's an updated desktop template coming out soon that includes the <pear-ctrl> element which also needs to be documented - heres the template update: https://github.com/holepunchto/pear/pull/28

**Comment by davidmarkclements** [comment]
re the background will look into thanks @mattdesl 🍐

**Comment by lukastanisic99** [comment]
Apart from MacOS the same issue also on Windows 10

**Comment by 4c656554** [comment]
I see the same issue on Ubuntu 22.04.4 LTS
