### ISSUE TITLE
Error Installing Pear Locally on macOS M2

### ISSUE THREAD

**Issue by mattdesl** [holepunchto/pear#31]
I'm trying to set up locally so that I can test (and potentially fix bugs like the background color etc) but running into trouble.

My steps:

- `npm install -g drives`
- `drives touch` (copy drive key)
- git clone, install the `pear` repo, then `npm run bootstrap <paste key>`
- I get a `./pear.dev` symlink, but it appears broken, running `./pear.dev` leads to "no such file" and running `file -L pear.dev` gives me `pear.dev: broken symbolic link to by-arch/darwin-arm64/bin/pear-runtime`

Any ideas?

**Comment by mafintosh** [comment]
Checkout the README now. I just updated the guide. Its super simple.

**Comment by mattdesl** [comment]
cool, got it working without `<KEY>`, I feel that might not be needed in the install instructions as it's not really clear what it means for first-timers to pear/holepunch ecosystem.
