### ISSUE TITLE
Cannot Run Two App Instances

### ISSUE THREAD

**Issue by mattdesl** [holepunchto/pear#33]
Going through this guide:
https://docs.pears.com/guides/making-a-pear-desktop-app

I can run the first app instance just fine and create a topic. However, running a second `pear dev` in a separate terminal window has no effect. If I close the dev app, then re-run the command it's fine, but again I can only ever have 1 instance running at a time.

**Comment by mafintosh** [comment]
Ya they are all single instance atm. To run two explicitly give the 2nd one a storage dir like so

```
pear dev -s /tmp/another-instance
```

PR to clarify that is super welcome (you are not the first one to be confused).

**Comment by mattdesl** [comment]
:+1: PR added to pear-desktop repo..

**Comment by davidmarkclements** [comment]
resolved
