### ISSUE TITLE
Error running pear terminal project example

### ISSUE THREAD

**Issue by markovAutomorphism** [holepunchto/pear#347]
Hi

I've been following this:

https://docs.pears.com/guides/starting-a-pear-terminal-project

I ran dev once before modifying the index.js and got a hex output. When I try again though I see this error

```bash
bare: undefined symbol: napi_set_last_error_info
```

When I try to do pear run pear://hex I see this error:

```bash
✖ The URL must use the file: protocol
✖ Error: Unknown [ code: (none) ] Error: The URL must use the file: protocol
    at fileURLToPath
```

What can I do to move forward?

**Comment by markovAutomorphism** [comment]
Desktop examples worked. I can just go from there maybe

**Comment by rafapaezbas** [comment]
Hello, this issue has been resolved with the latest platform release that uses Bare runtime 1.9.3. The platform should auto update and the terminal app will work.
