### ISSUE TITLE
pear release production -> null [production]

### ISSUE THREAD

**Issue by serapath** [holepunchto/pear#36]
Somehow typing `pear release production` always spits out `null [production]`
Is that how it is supposed to be?

How can I see the latest version or the names i staged and released an app to?
`pear info` seems to be malformatted or maybe has missing information or maybe i just don't understand how to read it.

I can type `pear stage dev` in two different apps, but what if i move a folder or rename it. It doesn't seem to save any data in package.json or a `.pear` folder inside my app project, so how does it know about my project?

I think I broke something by renaming my project folder later on.

Clearer docs or some bug fixes would be helpful :-)

**Comment by davidmarkclements** [comment]
@serapath the key for the app is based the app name+channel - the name of the app comes from package.json (but if you rename a folder and auto-update package.json name or something then it'll change the key) - but path shouldn't be part of it. For unusual circumstances you can override package.json name with the `--name` flag. `pear info` should be a lot clearer now with more info - `pear info <link>` will give you the channel name for an app. 

As for listing all channels that's an upcoming feature. Closing this as bugs are fixed, perpetually in agreement on clearer docs
