### ISSUE TITLE
custom cli scripts

### ISSUE THREAD

**Issue by HopeTS** [holepunchto/pear#46]
It would be great to add a pear equivalent to npm's "scripts" in package.json.

**Comment by davidmarkclements** [comment]
unlikely to do this, the future we're imagining of what dependency management looks like shouldn't need it (it's also a security hazard) - also on principal, avoid scripts if you can. if you have to use them, use npm. for spawning see the upcoming Pear.worker API - for many cases you can do your postinstall work inside an app init conditional check
