### ISSUE TITLE
ModuleError: MODULE_NOT_FOUND: Cannot find module 'node:process'

### ISSUE THREAD

**Issue by dabuchera** [holepunchto/pear#61]
I think this has already been discussed in the chat. Therefore just for documentation.

Using an external package which is using the global `node:process` gives the following error:

`ModuleError: MODULE_NOT_FOUND: Cannot find module 'node:process' imported from 'pear://dev/node_modules/@clack/prompts/dist/index.mjs'`

Using here [@clack/promps](https://www.npmjs.com/package/@clack/prompts)

**Comment by kasperisager** [comment]
We have a compatibility layer for Node.js builtins that you can use: https://github.com/holepunchto/bare-node

**Comment by dabuchera** [comment]
Hey @kasperisager 
Thank you! The error message no longer appears. Nevertheless, a strange behavior can now be observed. Running `pear dev .` on this example is not working. Only if the import is commented out.

`/* global Pear */
// Module for P2P networking and connecting peers
import b4a from 'b4a'
// Cryptographic functions for generating the key in app
import readline from 'bare-readline'
// Module for reading user input in terminal
import tty from 'bare-tty'
// Module for buffer-to-string and vice-versa conversions
import crypto from 'hypercore-crypto'
import Hyperswarm from 'hyperswarm'

// Wenn diese Zeile auskommentiert ist, funktioniert es
// import { cancel, isCancel, select } from '@clack/prompts' // Module for interactive prompts

/* if (Pear.config.dev) {
  const { Inspector } = await import('pear-inspect')
  const inspector = await new Inspector()
  const key = await inspector.enable()
  console.log(`Debug with pear://runtime/devtools/${key.toString('hex')}`)
} */

const { teardown, config } = Pear // Import configuration options and cleanup functions from Pear
const key = config.args.pop() // Retrieve a potential chat room key from command-line arguments
const shouldCreateSwarm = !key // Flag to determine if a new chat room should be created
const swarm = new Hyperswarm()

// Unannounce the public key before exiting the process
// (This is not a requirement, but it helps avoid DHT pollution)
teardown(() => swarm.destroy())

const rl = readline.createInterface({
  input: new tty.ReadStream(0),
  output: new tty.WriteStream(1),
})

// When there's a new connection, listen for new messages, and output them to the terminal
swarm.on('connection', (peer) => {
  const name = b4a.toString(peer.remotePublicKey, 'hex').substr(0, 6)
  console.log(`[info] New peer joined, ${name}`)
  peer.on('data', (message) => appendMessage({ name, message }))
  peer.on('error', (e) => console.log(`Connection error: ${e}`))
})

// When there's updates to the swarm, update the peers count
swarm.on('update', () => {
  console.log(`[info] Number of connections is now ${swarm.connections.size}`)
})

if (shouldCreateSwarm) {
  await createChatRoom()
} else {
  await joinChatRoom(key)
}

// rl.input.setMode(tty.constants.MODE_RAW) // Enable raw input mode for efficient key reading
rl.input.setMode(tty.constants.MODE_RAW) // Enable raw input mode for efficient key reading
rl.on('data', (line) => {
  sendMessage(line)
  rl.prompt()
})
rl.prompt()

async function createChatRoom() {
  // Generate a new random topic (32 byte string)
  const topicBuffer = crypto.randomBytes(32)
  // Create a new chat room for the topic
  await joinSwarm(topicBuffer)
  const topic = b4a.toString(topicBuffer, 'hex')
  console.log(`[info] Created new chat room: ${topic}`)
}

async function joinChatRoom(topicStr) {
  const topicBuffer = b4a.from(topicStr, 'hex')
  await joinSwarm(topicBuffer)
  console.log(`[info] Joined chat room`)
}

async function joinSwarm(topicBuffer) {
  // Join the swarm with the topic. Setting both client/server to true means that this app can act as both.
  const discovery = swarm.join(topicBuffer, { client: true, server: true })
  await discovery.flushed()
}

function sendMessage(message) {
  // Send the message to all peers (that you are connected to)
  const peers = [...swarm.connections]
  for (const peer of peers) peer.write(message)
}

function appendMessage({ name, message }) {
  // Output chat msgs to terminal
  console.log(`[${name}] ${message}`)
}
`

**Comment by kasperisager** [comment]
Pleasure! I think error handling in Pear might still be wonky, see #89. Loading `@clack/prompts` directly in Bare revealed that `tty.isatty()` was missing, I've added that here: https://github.com/holepunchto/bare-tty/commit/4e56a1386705a44ee2e7c2e1eac56a7e8b88b19b. Let me know if it does the trick!

**Comment by dabuchera** [comment]
Nice. Thanks for having a look. Unfortunately, it doesn't work yet.
Any approaches i could try out?

**Comment by kasperisager** [comment]
I'd try removing all the Pear bits to hopefully isolate the issue to either Bare or Pear.

**Comment by dabuchera** [comment]
Most likely Bare

**Comment by davidmarkclements** [comment]
closing as resolve per topic
