### ISSUE TITLE
500 Internal server error on pear dev

### ISSUE THREAD

**Issue by nitsaw09** [holepunchto/pear#66]
I am getting 500 internal server Error while running the Pear desktop application through ```pear dev```

I have done all the configuration for the pear and also added the pear path to the system path on windows
`C:\Users\{UserName}\AppData\Roaming\pear\bin`

On running the Pear app I am getting this error on the application console tab and getting blank screen on Pear runtime
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

`<html><head><meta name="color-scheme" content="light dark"></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">Cannot read properties of undefined (reading 'get')</pre></body></html>`

**Comment by mafintosh** [comment]
Hi! We have a new version going out on monday, let's check with that, but tracking this now thanks (heard this from another user also)

**Comment by davidmarkclements** [comment]
fixed
